#!/bin/bash

echo "🔧 Testing Session Persistence for Seller Categories"
echo "======================================================"
echo ""

# Colors
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${YELLOW}Step 1: Clean compile and restart${NC}"
cd /Users/hoangquangminh/Desktop/FUlearning/FALL25/SWP391/BanHangRong
./mvnw clean compile -DskipTests

echo ""
echo -e "${YELLOW}Step 2: Start application${NC}"
echo "Run in a separate terminal:"
echo "  ./mvnw spring-boot:run"
echo ""
echo "Wait for: 'Started Su25Application'"
echo ""

read -p "Press Enter when application is started..."

echo ""
echo -e "${YELLOW}Step 3: Manual Testing Steps${NC}"
echo "======================================================"
echo ""
echo "1. Open browser: http://localhost:8080/login"
echo "2. Login with seller account"
echo "3. Check terminal logs for:"
echo "   - '=== Authentication Success ==='"
echo "   - 'Session ID: ...'"
echo "   - 'Session MaxInactiveInterval: 28800'"
echo ""
echo "4. After login, you should be at: /seller/dashboard"
echo ""
echo "5. Check browser cookies (DevTools → Application → Cookies):"
echo "   - JSESSIONID should exist"
echo "   - Note the Session ID"
echo ""
echo "6. Test endpoint: http://localhost:8080/seller/categories/test"
echo "   Expected: 'TEST OK - Session ID: ..., User: [username]'"
echo ""
echo "7. Click 'Quản lý Danh mục' in sidebar"
echo "   URL should be: /seller/categories"
echo ""
echo "8. Check terminal logs for:"
echo "   '🔍 SellerCategoryController.categoryManagementPage() CALLED'"
echo "   'Current user from session: [username]'"
echo ""
echo "9. If redirected to login:"
echo "   - Check logs for '❌ User is NULL'"
echo "   - Check if Session ID changed"
echo "   - Check browser cookies still have JSESSIONID"
echo ""

echo -e "${YELLOW}Step 4: Debug Checklist${NC}"
echo "======================================================"
echo ""
echo "If still redirected to login, check:"
echo ""
echo "□ Terminal logs show method being called?"
echo "□ Session ID is the same between requests?"
echo "□ JSESSIONID cookie exists in browser?"
echo "□ Logs show 'User is NULL'?"
echo "□ Any Spring Security errors in logs?"
echo ""

echo -e "${YELLOW}Step 5: SQL Verification${NC}"
echo "======================================================"
echo ""
echo "Check if user exists and has correct type:"
echo ""
echo "mysql -u root -p wap << 'SQL'"
echo "SELECT user_id, username, user_type, last_login"
echo "FROM users"
echo "WHERE username = 'YOUR_SELLER_USERNAME';"
echo "SQL"
echo ""

echo -e "${YELLOW}Step 6: Browser Console Test${NC}"
echo "======================================================"
echo ""
echo "In browser console, run:"
echo ""
echo "// Check cookies"
echo "document.cookie"
echo ""
echo "// Test API endpoint"
echo "fetch('/seller/categories/test')"
echo "  .then(r => r.text())"
echo "  .then(console.log)"
echo ""

echo ""
echo -e "${GREEN}Testing complete!${NC}"
echo "If issue persists, check the logs carefully."

