#!/bin/bash

# Security Test Script for Review Isolation
# Tests that each seller only sees their own product reviews

echo "=========================================="
echo "🔒 SECURITY TEST: Review Isolation"
echo "=========================================="
echo ""

echo "This script helps you verify that:"
echo "✓ Each seller only sees reviews for their own products"
echo "✓ Cannot see reviews of other sellers"
echo "✓ Empty state works when no reviews exist"
echo ""

echo "=========================================="
echo "📋 PRE-TEST SETUP"
echo "=========================================="
echo ""

echo "1️⃣ Create Test Sellers in Database:"
echo ""
echo "   Run these SQL commands:"
echo ""
echo "   -- Create Seller 1"
echo "   INSERT INTO users (username, email, password, user_type, full_name, is_email_verified, is_active)"
echo "   VALUES ('testseller1', 'seller1@test.com', '\$2a\$10\$hash', 'SELLER', 'Test Seller One', true, true);"
echo ""
echo "   -- Create Seller 2"
echo "   INSERT INTO users (username, email, password, user_type, full_name, is_email_verified, is_active)"
echo "   VALUES ('testseller2', 'seller2@test.com', '\$2a\$10\$hash', 'SELLER', 'Test Seller Two', true, true);"
echo ""
echo "   -- Create Customer"
echo "   INSERT INTO users (username, email, password, user_type, full_name, is_email_verified, is_active)"
echo "   VALUES ('testcustomer', 'customer@test.com', '\$2a\$10\$hash', 'CUSTOMER', 'Test Customer', true, true);"
echo ""

echo "2️⃣ Create Test Products:"
echo ""
echo "   -- Product for Seller 1 (get seller_id from users table)"
echo "   INSERT INTO products (product_name, description, price, stock, seller_id, category_id)"
echo "   VALUES ('Product A from Seller 1', 'Test product', 100, 10, <seller1_id>, 1);"
echo ""
echo "   -- Product for Seller 2"
echo "   INSERT INTO products (product_name, description, price, stock, seller_id, category_id)"
echo "   VALUES ('Product B from Seller 2', 'Test product', 200, 20, <seller2_id>, 1);"
echo ""

echo "3️⃣ Create Test Reviews:"
echo ""
echo "   -- Review for Seller 1's product"
echo "   INSERT INTO product_reviews (product_id, user_id, rating, comment, created_at)"
echo "   VALUES (<product_a_id>, <customer_id>, 5, 'Great product from Seller 1!', NOW());"
echo ""
echo "   -- Another review for Seller 1's product"
echo "   INSERT INTO product_reviews (product_id, user_id, rating, comment, created_at)"
echo "   VALUES (<product_a_id>, <customer_id>, 4, 'Good quality from Seller 1', NOW());"
echo ""
echo "   -- Review for Seller 2's product"
echo "   INSERT INTO product_reviews (product_id, user_id, rating, comment, created_at)"
echo "   VALUES (<product_b_id>, <customer_id>, 5, 'Excellent product from Seller 2!', NOW());"
echo ""
echo "   -- Another review for Seller 2's product"
echo "   INSERT INTO product_reviews (product_id, user_id, rating, comment, created_at)"
echo "   VALUES (<product_b_id>, <customer_id>, 3, 'Average product from Seller 2', NOW());"
echo ""

echo "=========================================="
echo "🧪 TEST CASES"
echo "=========================================="
echo ""

echo "TEST 1: Seller 1 Sees Only Their Reviews"
echo "─────────────────────────────────────────"
echo "Steps:"
echo "  1. Login as: testseller1"
echo "  2. Go to: http://localhost:8080/seller/reviews"
echo "  3. Verify you see:"
echo "     ✓ 'Great product from Seller 1!'"
echo "     ✓ 'Good quality from Seller 1'"
echo "     ✓ Total Reviews: 2"
echo "  4. Verify you DO NOT see:"
echo "     ✗ 'Excellent product from Seller 2!'"
echo "     ✗ 'Average product from Seller 2'"
echo ""
echo "Expected Result: ✅ PASS - Only Seller 1's reviews visible"
echo ""

echo "TEST 2: Seller 2 Sees Only Their Reviews"
echo "─────────────────────────────────────────"
echo "Steps:"
echo "  1. Logout from Seller 1"
echo "  2. Login as: testseller2"
echo "  3. Go to: http://localhost:8080/seller/reviews"
echo "  4. Verify you see:"
echo "     ✓ 'Excellent product from Seller 2!'"
echo "     ✓ 'Average product from Seller 2'"
echo "     ✓ Total Reviews: 2"
echo "  5. Verify you DO NOT see:"
echo "     ✗ 'Great product from Seller 1!'"
echo "     ✗ 'Good quality from Seller 1'"
echo ""
echo "Expected Result: ✅ PASS - Only Seller 2's reviews visible"
echo ""

echo "TEST 3: Empty State for New Seller"
echo "─────────────────────────────────────────"
echo "Steps:"
echo "  1. Create new seller: testseller3 (with no products)"
echo "  2. Login as: testseller3"
echo "  3. Go to: http://localhost:8080/seller/reviews"
echo "  4. Verify you see:"
echo "     ✓ 'No reviews found'"
echo "     ✓ Total Reviews: 0"
echo "     ✓ Pending Response: 0"
echo "     ✓ Responded: 0"
echo ""
echo "Expected Result: ✅ PASS - Empty state displayed"
echo ""

echo "TEST 4: Customer Cannot Access Seller Reviews"
echo "─────────────────────────────────────────"
echo "Steps:"
echo "  1. Login as: testcustomer"
echo "  2. Try to access: http://localhost:8080/seller/reviews"
echo "  3. Verify:"
echo "     ✓ Redirects to /login?error=unauthorized"
echo "     ✓ Cannot view seller review page"
echo ""
echo "Expected Result: ✅ PASS - Access denied"
echo ""

echo "TEST 5: Unauthenticated User Cannot Access"
echo "─────────────────────────────────────────"
echo "Steps:"
echo "  1. Logout completely"
echo "  2. Try to access: http://localhost:8080/seller/reviews"
echo "  3. Verify:"
echo "     ✓ Redirects to /login?error=notAuthenticated"
echo "     ✓ Must login to access"
echo ""
echo "Expected Result: ✅ PASS - Must authenticate"
echo ""

echo "TEST 6: Cannot Respond to Another Seller's Review"
echo "─────────────────────────────────────────"
echo "Steps:"
echo "  1. Login as: testseller1"
echo "  2. Find review_id of Seller 2's review from database:"
echo "     SELECT review_id FROM product_reviews pr"
echo "     JOIN products p ON pr.product_id = p.product_id"
echo "     WHERE p.seller_id = <seller2_id> LIMIT 1;"
echo "  3. Try to respond via browser console:"
echo "     fetch('/seller/reviews/respond/<review_id>', {"
echo "       method: 'POST',"
echo "       headers: {'Content-Type': 'application/json'},"
echo "       body: JSON.stringify({response: 'Trying to hijack'})"
echo "     })"
echo "  4. Verify response:"
echo "     ✓ Status: 403 Forbidden"
echo "     ✓ Message: 'You do not have permission to respond to this review'"
echo ""
echo "Expected Result: ✅ PASS - Cannot respond to other seller's reviews"
echo ""

echo "=========================================="
echo "🔍 DATABASE VERIFICATION QUERIES"
echo "=========================================="
echo ""

echo "Query 1: Check Reviews by Seller"
echo "─────────────────────────────────"
echo "SELECT "
echo "    u.username as seller_name,"
echo "    p.product_name,"
echo "    pr.review_id,"
echo "    pr.comment,"
echo "    pr.rating"
echo "FROM product_reviews pr"
echo "JOIN products p ON pr.product_id = p.product_id"
echo "JOIN users u ON p.seller_id = u.user_id"
echo "ORDER BY u.username, pr.created_at DESC;"
echo ""

echo "Query 2: Count Reviews per Seller"
echo "─────────────────────────────────"
echo "SELECT "
echo "    u.username as seller_name,"
echo "    COUNT(pr.review_id) as total_reviews,"
echo "    SUM(CASE WHEN pr.seller_response IS NULL THEN 1 ELSE 0 END) as pending,"
echo "    SUM(CASE WHEN pr.seller_response IS NOT NULL THEN 1 ELSE 0 END) as responded"
echo "FROM users u"
echo "LEFT JOIN products p ON u.user_id = p.seller_id"
echo "LEFT JOIN product_reviews pr ON p.product_id = pr.product_id"
echo "WHERE u.user_type = 'SELLER'"
echo "GROUP BY u.user_id, u.username"
echo "ORDER BY u.username;"
echo ""

echo "Query 3: Verify No Cross-Seller Access"
echo "─────────────────────────────────"
echo "-- This should return 0 rows (security check)"
echo "SELECT pr.review_id, pr.comment, p1.seller_id as review_seller, p2.seller_id as different_seller"
echo "FROM product_reviews pr"
echo "JOIN products p1 ON pr.product_id = p1.product_id"
echo "CROSS JOIN products p2"
echo "WHERE p1.seller_id != p2.seller_id"
echo "AND pr.review_id IN ("
echo "    SELECT review_id FROM product_reviews"
echo "    JOIN products ON product_reviews.product_id = products.product_id"
echo "    WHERE products.seller_id = p2.seller_id"
echo ");"
echo ""

echo "=========================================="
echo "✅ EXPECTED TEST RESULTS SUMMARY"
echo "=========================================="
echo ""
echo "✓ TEST 1: PASS - Seller 1 sees only their 2 reviews"
echo "✓ TEST 2: PASS - Seller 2 sees only their 2 reviews"
echo "✓ TEST 3: PASS - New seller sees empty state"
echo "✓ TEST 4: PASS - Customer redirected to login"
echo "✓ TEST 5: PASS - Unauthenticated user redirected"
echo "✓ TEST 6: PASS - Cannot respond to other's reviews"
echo ""
echo "If ALL tests pass: 🎉 Security implementation is CORRECT!"
echo ""

echo "=========================================="
echo "🐛 TROUBLESHOOTING"
echo "=========================================="
echo ""
echo "Problem: Seller sees reviews from other sellers"
echo "Solution:"
echo "  1. Check if database queries include JOIN with products table"
echo "  2. Verify WHERE clause includes: WHERE p.seller_id = :sellerId"
echo "  3. Check ProductReviewsRepository.java for all queries"
echo ""
echo "Problem: Empty state not showing"
echo "Solution:"
echo "  1. Verify Thymeleaf condition: th:if=\"\${reviews.isEmpty()}\""
echo "  2. Check if seller has products but no reviews"
echo "  3. Verify seller authentication (session.getAttribute('userId'))"
echo ""
echo "Problem: Can respond to other seller's reviews"
echo "Solution:"
echo "  1. Check isReviewOwnedBySeller() method"
echo "  2. Verify ownership check query includes seller_id filter"
echo "  3. Check SellerReviewController security validations"
echo ""

echo "=========================================="
echo "📝 MANUAL TESTING CHECKLIST"
echo "=========================================="
echo ""
echo "[ ] Setup complete (sellers, products, reviews created)"
echo "[ ] TEST 1 passed - Seller 1 isolation verified"
echo "[ ] TEST 2 passed - Seller 2 isolation verified"
echo "[ ] TEST 3 passed - Empty state works"
echo "[ ] TEST 4 passed - Customer cannot access"
echo "[ ] TEST 5 passed - Authentication required"
echo "[ ] TEST 6 passed - Cannot hijack reviews"
echo "[ ] Database queries verified"
echo "[ ] All security checks passed"
echo ""

echo "=========================================="
echo "🎯 Security Testing Complete!"
echo "=========================================="
echo ""
echo "Run this checklist after each deployment to ensure"
echo "review isolation security remains intact."
echo ""

