#!/bin/bash

# Test Script for Review Management System Updates
# This script helps verify all changes are working correctly

echo "========================================"
echo "Review Management System - Test Guide"
echo "========================================"
echo ""

echo "📋 CHECKLIST - Test these items:"
echo ""

echo "1️⃣ Customer Name Display"
echo "   □ Log in as a seller"
echo "   □ Navigate to /seller/reviews"
echo "   □ Verify you see customer names (not User IDs)"
echo "   □ Check if 'Anonymous' appears for users without names"
echo ""

echo "2️⃣ English Translation"
echo "   □ Page title is 'Review & Response Management'"
echo "   □ KPI cards show 'Total Reviews', 'Pending Response', 'Responded'"
echo "   □ Buttons say 'Apply filters', 'Clear filters', 'Send response'"
echo "   □ No Vietnamese text visible anywhere"
echo ""

echo "3️⃣ Response Saving"
echo "   □ Find a review without a response"
echo "   □ Type a response in the textarea"
echo "   □ Click 'Send response'"
echo "   □ Success message appears: 'Response sent successfully!'"
echo "   □ Response displays immediately below the review"
echo "   □ Badge changes from 'Pending Response' to 'Responded'"
echo "   □ Refresh the page - response is still there"
echo ""

echo "4️⃣ Database Verification"
echo "   □ Open your database client"
echo "   □ Run: SELECT * FROM product_reviews WHERE seller_response IS NOT NULL;"
echo "   □ Verify seller_response and seller_response_at are populated"
echo ""

echo "5️⃣ Filters Still Work"
echo "   □ Click 'Pending Response' card - shows only unanswered"
echo "   □ Click 'Responded' card - shows only answered"
echo "   □ Try advanced filters (rating, date range)"
echo "   □ Clear filters - shows all reviews"
echo ""

echo "6️⃣ Error Handling (English)"
echo "   □ Try to submit empty response - shows 'Please enter response content'"
echo "   □ Try date filter with invalid range - shows proper English error"
echo "   □ All error messages in English"
echo ""

echo "========================================"
echo "🚀 Start Application"
echo "========================================"
echo ""
echo "Run one of these commands to start:"
echo ""
echo "Option 1 - Online Database:"
echo "  ./mvnw spring-boot:run"
echo ""
echo "Option 2 - H2 Database:"
echo "  ./run-with-h2.sh"
echo ""

echo "========================================"
echo "📊 Sample SQL Queries"
echo "========================================"
echo ""
echo "1. Check reviews with customer names:"
echo "   SELECT pr.review_id, pr.comment, pr.rating, u.full_name, u.username"
echo "   FROM product_reviews pr"
echo "   JOIN users u ON pr.user_id = u.user_id"
echo "   LIMIT 10;"
echo ""
echo "2. Check seller responses:"
echo "   SELECT review_id, seller_response, seller_response_at"
echo "   FROM product_reviews"
echo "   WHERE seller_response IS NOT NULL;"
echo ""
echo "3. Get reviews for specific seller:"
echo "   SELECT pr.*, p.product_name, u.full_name as customer_name"
echo "   FROM product_reviews pr"
echo "   JOIN products p ON pr.product_id = p.product_id"
echo "   JOIN users u ON pr.user_id = u.user_id"
echo "   WHERE p.seller_id = 1;"
echo ""

echo "========================================"
echo "✅ Expected Results"
echo "========================================"
echo ""
echo "✓ Customer names appear instead of 'User ID: X'"
echo "✓ All text is in English"
echo "✓ Responses save to database permanently"
echo "✓ UI updates immediately after responding"
echo "✓ All filters continue to work"
echo "✓ Pagination works correctly"
echo "✓ Error messages are in English"
echo ""

echo "========================================"
echo "🐛 Troubleshooting"
echo "========================================"
echo ""
echo "Issue: 'Anonymous' shows for all customers"
echo "  → Check if users have full_name in database"
echo "  → Run: SELECT user_id, username, full_name FROM users;"
echo ""
echo "Issue: Responses don't save"
echo "  → Check browser console for errors"
echo "  → Verify CSRF token is being sent"
echo "  → Check server logs for exceptions"
echo ""
echo "Issue: Vietnamese text still appears"
echo "  → Clear browser cache (Cmd+Shift+R)"
echo "  → Check if correct template is being loaded"
echo ""

echo "========================================"
echo "📝 Manual Test Case"
echo "========================================"
echo ""
echo "1. Login as seller (e.g., seller1/password123)"
echo "2. Go to http://localhost:8080/seller/reviews"
echo "3. Find any review"
echo "4. Verify format: 'Customer Name • Date' (not User ID)"
echo "5. If no response exists, add one:"
echo "   - Type: 'Thank you for your feedback!'"
echo "   - Click 'Send response'"
echo "6. Verify:"
echo "   - Success message appears"
echo "   - Response displays below review"
echo "   - Badge changes to 'Responded'"
echo "7. Refresh page"
echo "8. Verify response is still there (saved to DB)"
echo ""

echo "========================================"
echo "✨ All changes complete!"
echo "========================================"

